# Generated by Django 4.2.3 on 2023-07-14 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ecent_description',
            new_name='event_description',
        ),
    ]
